config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  resources :users ,path_names: { create: 'make' } do
    resources :plants do
      resources :growth_records, shallow: true
    end
  end
  
  scope 'username' do
    resources :users, only: [:create]
  end

  #レスポンスのデフォルトフォーマットをJSONに変更
  defaults format: :json do
    resources :users
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/growth_record.rb
class GrowthRecord < ApplicationRecord
  belongs_to :plant
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :growth_record
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# 以下を追記
before_action :configure_permitted_parameters, if: :devise_controller?

# ここから
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
end
# ここまで追記
end

app/controllers/growth_records_controller.rb
class GrowthRecordsController < ApplicationController

  # before_action :move_to_index, except: [:index, :show]

  def index
    @user = User.find(params[:user_id])
    @plants = @user.plants
    @growth_record = @plants.growth_record
    #binding.pry
  end

  # def move_to_index
  #   # 自分以外のユーザーの植物の 編集/削除/新規作成はできない
  #   if (user_signed_in?)    
  #     if (params[:user_id].to_i != current_user.id)
  #       redirect_to action: :index
  #     end
  #   elsif
  #       redirect_to action: :index
  #   end
  # end

  def new
    @user = User.find(params[:user_id])
    @plant = Plant.find(params[:plant_id])
    @growth_record = GrowthRecord.new
    # binding.pry
  end

  def create
    @growth_record = GrowthRecord.new(record_params)
    @plant = Plant.find(params[:plant_id])
    @plant.growth_record.create(record_params)
    # binding.pry
  end

  def show

  end

  def edit
    @growth_record = GrowthRecord.find(params[:id])
  end

  def update
    @growth_record = GrowthRecord.find(params[:id])
    @growth_record.update(record_params)
    # binding.pry
  end

  def destroy
    @growth_record = GrowthRecord.find(params[:id])
    @growth_record.destroy
    # binding.pry
  end

  private
  def record_params
    params.require(:growth_record).permit(:temp, :humid)
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @plants = Plant.all

    @user = User.find(params[:user_id])
    @plants = @user.plants
    #binding.pry
  end
  
  def move_to_index
    # 自分以外のユーザーの植物の 編集/削除/新規作成はできない
    if (user_signed_in?)    
      if (params[:user_id].to_i != current_user.id)
        redirect_to action: :index
      end
    elsif
        redirect_to action: :index
    end
  end

  def new
    @user = User.find(params[:user_id])
    @plant = Plant.new
    #binding.pry
  end

  def create
    binding.pry
    @plant = Plant.new(plant_params)

    current_user.plants.create(plant_params)
    
  end

  def show
    @user = User.find(params[:user_id])
    @plant = @user.plants.find(params[:id])
    @growth_record = @plant.growth_record

  end

  def edit
    @user = User.find(params[:user_id])
    @plant = @user.plants.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @plant = @user.plants.find(params[:id])
    @plant.update(plant_params)
  end

  def destroy
    #binding.pry
    #@plant = @user.plants.find(params[:id])
    @plant = current_user.plants.find(params[:id])
    #binding.pry
    @plant.destroy

  end

  private
  def plant_params
    params.require(:plant).permit(:user_id, :plant_name, :img)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    # binding.pry
  end

  def new
    @user = User.new
    # binding.pry
  end

  def create
    # binding.pry
    User.create!(user_params)    
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def show
    @user = User.find(params[:id])
    # binding.pry
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    # binding.pry
  end

  private
  def user_params
    params.require(:user).permit(:password, :nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/growth_records_helper.rb
module GrowthRecordsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/growth_records/create.html.erb
<h1>登録完了</h1>
<%= link_to '詳細ページ', user_plant_path(current_user.id,@plant.id) %>

app/views/growth_records/destroy.html.erb
<h1>削除完了</h1>
<%= link_to '詳細ページ', user_plant_path(current_user.id,@growth_record.plant_id) %>

app/views/growth_records/edit.html.erb
<h1>計測記録-編集</h1>
<%= form_with model: @growth_record, local: true do |f| %>
  <p>温度：<%= f.text_field :temp %></p>
  <p>湿度：<%= f.text_field :humid %></p>
  <%= f.submit "修正" %>
<% end %>

app/views/growth_records/new.html.erb
<h1>温度湿度-新規登録</h1>
<%= form_with model: [@user, @plant,@growth_record], local: true do |f| %>
  <p>温度：<%= f.text_field :temp %></p>
  <p>湿度：<%= f.text_field :humid %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/growth_records/update.html.erb
<h1>修正完了</h1>
<%= link_to '詳細ページ', user_plant_path(current_user.id,@growth_record.plant_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WakuwakuPlant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- ここから -->
  <%= javascript_pack_tag 'hello_vue' %>
  <%= stylesheet_pack_tag 'hello_vue'  %> 
  
  <%= link_to "ユーザー一覧", users_path %>
    <% if user_signed_in? %>
      <%= link_to 'マイページへ', user_path(current_user.id) %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
    <div id="hello">
      <app></app>
    </div>

    <!-- ここまで -->
  </body>
</html>

app/views/plants/create.html.erb
<h1>登録完了</h1>
<%= link_to 'マイページへ', user_path(current_user.id) %>

app/views/plants/edit.html.erb
<h1>植物-編集</h1>
<%= form_with model: [@user, @plant], local: true do |f| %>
  <p>植物名：<%= f.text_field :plant_name %></p>
  <%= f.submit "修正" %>
<% end %>

app/views/plants/index.html.erb
<h1>植物一覧</h1>
<% if user_signed_in? %>
  <% @plants.each do |plant| %>
    <p>名前：<%= plant.plant_name %> ユーザーID：<%= plant.user_id %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/plants/new.html.erb
<h1>植物-新規登録</h1>
<%= form_with model: [@user, @plant], local: true do |f| %>
  <p>植物名：<%= f.text_field :plant_name %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/plants/show.html.erb
<h1>植物　詳細</h1>
<h3>植物の名前</h3>
<%= @plant.plant_name %><br>
<h3> 植物の写真　</h3>
<%= @plant.img %><br>
<h3> 温度/湿度　</h3>
<% if user_signed_in? %>
  <%= link_to '温度/湿度　登録' ,new_user_plant_growth_record_path(plant_id: @plant.id) %>
<% end %>

<% @growth_record.each do |g| %>
  <li>日時：<%= g.record_time %> / 　温度：<%= g.temp %>  /湿度：<%= g.humid %>  </li> 
  <% if user_signed_in? %>
    <% if current_page?(user_plant_path(@plant.id)) %> 
      <%= link_to "編集", [:edit, g] %> 
      <%= link_to "削除", g, method: :delete, data: {confirm: "削除しますか?"} %> </li>
    <% end %>
  <% end %>
<% end %>

app/views/plants/update.html.erb
<h1>更新完了</h1>
<%= link_to 'マイページへ', user_path(current_user.id) %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
サンプルユーザー：
mail:test@example.com<br>
pass:password<br>
<% @users.each do |user| %>
<p>ニックネーム <%= link_to user.nickname, user %></p>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <% if current_page?(user_path(current_user.id)) %>
  <h1>マイページ</h1>
  <% else %>
  <h1>ユーザー　詳細</h1>
  <% end %>
<% else %>
<h1>ユーザー　詳細</h1>
<% end %>

<h3>ニックネーム</h3>
<%= @user.nickname %><br>
<h3>メールアドレス</h3>
<%= @user.email %><br>
<h3> 所有している植物　</h3>
<% @user.plants.each do |p| %>
  <li><%= link_to p.plant_name ,[@user,p]%> 
  <% if user_signed_in? %>
    <% if current_page?(user_path(current_user.id)) %> 
      <%= link_to "編集", [:edit, @user,p] %> 
      <%= link_to "削除", [@user,p], method: :delete, data: {confirm: "削除しますか?"} %> </li>
    <% end %>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <% if current_page?(user_path(current_user.id)) %>
  <br>
  <%= link_to '植物登録' ,new_user_plant_path(current_user.id) %>

  <% end %>
<% end %>